@startuml
package System {
  class OdinSystem {
    Boolean learnedFlag
    Boolean randomFlag
    Integer listSize
    Integer listIndex
    + OdinSystem updateIndex()
    + OdinSystem resetIndex()
  }
}
package Application {
  class Term {
    Long identifier
    Word word
    Meaning meaning
    LearnedState learnedFlag
  }
  class Word {
    String name
  }
  class Meaning {
    String context
  }
  enum LearnedState {
    NOT_LEARNED
    LEARNED
  }
  Term o-- Word
  Term o-- Meaning
  Term -> LearnedState
}

Application -- System

@enduml